import path from 'node:path';
import type { OutputFormat } from '../config/schema.js';
import type { Diagram } from '../diagrams/ir.js';
import type { Renderer } from '../render/renderer.js';
import { shortHash } from '../core/hash.js';

/**
 * Diagram output files contain a UMLFlow-generated block and user-owned
 * content. Regeneration replaces only the generated block; a manual section
 * inside the diagram and everything outside the generated block survive.
 */

export const MD_GEN_BEGIN = '<!-- UMLFLOW GENERATED BEGIN — do not edit inside this block; run `umlflow update` -->';
export const MD_GEN_END = '<!-- UMLFLOW GENERATED END -->';
export const MD_MANUAL_BEGIN = '<!-- UMLFLOW MANUAL BEGIN — your notes below are preserved -->';
export const MD_MANUAL_END = '<!-- UMLFLOW MANUAL END -->';
export const DIAGRAM_MANUAL_BEGIN = 'UMLFLOW MANUAL BEGIN';
export const DIAGRAM_MANUAL_END = 'UMLFLOW MANUAL END';
const GEN_BEGIN_RE = /<!--\s*UMLFLOW GENERATED BEGIN[^\n]*-->/;
const GEN_END_RE = /<!--\s*UMLFLOW GENERATED END\s*-->/;

export interface ComposeInput {
  diagram: Diagram;
  rendered: string;
  renderer: Renderer;
  format: OutputFormat;
  /** Lines the user placed inside the diagram's manual section previously. */
  manualDiagramLines: string[];
}

export function outputFileName(name: string, format: OutputFormat, renderer: Renderer): string {
  return format === 'md' ? `${name}.md` : `${name}.${renderer.extension}`;
}

/**
 * Repo-relative path of a diagram's plain-Mermaid mirror, grouped by diagram
 * type: `<mermaidDir>/<type>/<name>.<ext>`.
 */
export function mermaidMirrorFileName(mermaidDir: string, type: string, name: string, renderer: Renderer): string {
  return path.posix.join(mermaidDir, type, `${name}.${renderer.extension}`);
}

/**
 * The bare diagram for the mirror: no generated/manual markers and no Markdown,
 * just a provenance header comment and the rendered diagram. Fully derived —
 * the file under `output.dir` stays the editable one.
 */
export function composeMermaidMirror(input: { diagram: Diagram; rendered: string; renderer: Renderer; sourceFile: string }): string {
  const c = input.renderer.commentPrefix;
  const header = [
    `${c} ${input.diagram.title}`,
    `${c} Generated by UMLFlow from the source code. Do not edit: this file is a mirror of`,
    `${c} ${input.sourceFile} and is overwritten on every \`umlflow update\`.`,
  ];
  return [...header, input.rendered.replace(/\n+$/, '')].join('\n') + '\n';
}

/** Insert the in-diagram manual section (renderer comment markers) before the trailing newline. */
export function withManualSection(rendered: string, renderer: Renderer, manualLines: string[]): string {
  const c = renderer.commentPrefix;
  const body = rendered.replace(/\n+$/, '');
  const section = [`  ${c} ${DIAGRAM_MANUAL_BEGIN}`, ...manualLines, `  ${c} ${DIAGRAM_MANUAL_END}`];
  return `${body}\n${section.join('\n')}\n`;
}

export function composeGeneratedBlock(input: ComposeInput): string {
  const { diagram, renderer, format } = input;
  const diagramText = withManualSection(input.rendered, renderer, input.manualDiagramLines);
  if (format === 'mmd') {
    const c = renderer.commentPrefix;
    const lines = [
      `${c} UMLFLOW GENERATED BEGIN — generated by UMLFlow from source code; do not edit outside the MANUAL section`,
      `${c} ${diagram.title}`,
      ...diagram.notes.map((n) => `${c} note[${n.level}]: ${n.text}`),
      diagramText.replace(/\n$/, ''),
      `${c} UMLFLOW GENERATED END`,
    ];
    return lines.join('\n') + '\n';
  }
  const notes = diagram.notes.length
    ? ['', '**Analysis notes**', '', ...diagram.notes.map((n) => `- ${n.level === 'unknown' ? '❓' : n.level === 'inferred' ? '≈' : 'ℹ'} ${n.text}`)]
    : [];
  return [MD_GEN_BEGIN, '```' + renderer.fenceLanguage, diagramText.replace(/\n$/, ''), '```', ...notes, MD_GEN_END].join('\n') + '\n';
}

/** Extract the previously generated block, or null when the file has none. */
export function extractGeneratedBlock(text: string, format: OutputFormat, renderer: Renderer): string | null {
  if (format === 'md') {
    const begin = text.search(GEN_BEGIN_RE);
    const endMatch = GEN_END_RE.exec(text);
    if (begin < 0 || !endMatch) return null;
    const end = endMatch.index + endMatch[0].length;
    return text.slice(begin, end) + '\n';
  }
  const c = renderer.commentPrefix;
  const begin = text.indexOf(`${c} UMLFLOW GENERATED BEGIN`);
  const endMarker = `${c} UMLFLOW GENERATED END`;
  const end = text.indexOf(endMarker);
  if (begin < 0 || end < 0) return null;
  return text.slice(begin, end + endMarker.length) + '\n';
}

/** Lines between the in-diagram manual markers, or [] when absent. */
export function extractManualDiagramLines(text: string | null, renderer: Renderer): string[] {
  if (!text) return [];
  const c = renderer.commentPrefix;
  const lines = text.split('\n');
  const start = lines.findIndex((l) => l.trim() === `${c} ${DIAGRAM_MANUAL_BEGIN}`);
  const end = lines.findIndex((l, i) => i > start && l.trim() === `${c} ${DIAGRAM_MANUAL_END}`);
  if (start < 0 || end < 0) return [];
  return lines.slice(start + 1, end);
}

/** Fingerprint of generated content ignoring the manual section (so user edits there are not "staleness"). */
export function generatedFingerprint(block: string, renderer: Renderer): string {
  const c = renderer.commentPrefix;
  const lines = block.split('\n');
  const start = lines.findIndex((l) => l.trim() === `${c} ${DIAGRAM_MANUAL_BEGIN}`);
  const end = lines.findIndex((l, i) => i > start && l.trim() === `${c} ${DIAGRAM_MANUAL_END}`);
  const filtered = start >= 0 && end >= 0 ? [...lines.slice(0, start + 1), ...lines.slice(end)] : lines;
  return shortHash(filtered.join('\n'));
}

export interface MergeInput {
  existing: string | null;
  block: string;
  format: OutputFormat;
  renderer: Renderer;
  name: string;
  title: string;
  description?: string;
}

/** Produce the full file text, replacing only the generated block. */
export function mergeOutput(input: MergeInput): string {
  const { existing, block, format, renderer } = input;
  if (existing === null) return newFile(input);
  if (format === 'md') {
    const begin = existing.search(GEN_BEGIN_RE);
    const endMatch = GEN_END_RE.exec(existing);
    if (begin < 0 || !endMatch) {
      // Unknown file without markers: never destroy it — append the generated block.
      return existing.replace(/\n*$/, '\n\n') + block;
    }
    const end = endMatch.index + endMatch[0].length;
    const after = existing.slice(end).replace(/^\n/, '');
    return existing.slice(0, begin) + block + after;
  }
  const c = renderer.commentPrefix;
  const begin = existing.indexOf(`${c} UMLFLOW GENERATED BEGIN`);
  const endMarker = `${c} UMLFLOW GENERATED END`;
  const end = existing.indexOf(endMarker);
  if (begin < 0 || end < 0) return block; // a .mmd file must be a single diagram; markers missing means UMLFlow did not write it
  const after = existing.slice(end + endMarker.length).replace(/^\n/, '');
  return existing.slice(0, begin) + block + after;
}

function newFile(input: MergeInput): string {
  if (input.format === 'mmd') return input.block;
  const header = [`# ${input.title}`, ''];
  if (input.description) header.push(`> ${input.description}`, '');
  header.push(`_Generated by [UMLFlow](https://github.com/umlflow) from the source code — the code is the source of truth. Edit \`.umlflow/config.yaml\` to customise; use the manual sections for notes._`, '');
  return [...header, input.block, MD_MANUAL_BEGIN, '', MD_MANUAL_END, ''].join('\n');
}
